import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { ArrowRight, Compass, Lightbulb, MapPin, Users } from "lucide-react";
import { LandingNav } from "@/components/landing/landing-nav";
import { LandingFooter } from "@/components/landing/landing-footer";
import { MobileCarousel } from "@/components/shared/mobile-carousel";
import ScrollMotion from "@/components/shared/scroll-motion";

export const metadata: Metadata = {
  title: "About Us",
  description: "Learn about LEA Labs, a technology company building useful digital products, supporting organisations, and creating practical learning pathways.",
};

const ABOUT_HERO_IMAGE = "https://leasystem-jgtiwg7u.manus.space/manus-storage/lea-community-launch_f1ae296d.jpg";
const MENTOR_IMAGE = "https://leasystem-jgtiwg7u.manus.space/manus-storage/lea-mentor-support_9d78971d.jpg";

const values = [
  { title: "Collaborative Ownership", text: "We take responsibility for the work and move further together. We share context, support one another, and make progress visible across the team." },
  { title: "Innovation First", text: "We stay curious, test ideas, and create useful solutions. We turn thoughtful experiments into products and experiences that solve real problems." },
  { title: "Sustainability", text: "We build for lasting value and responsible growth. We consider the people, resources, and communities that need our work to keep serving them well." },
  { title: "Continuous Learning And Impact", text: "We keep learning and apply it where it matters. Every project is a chance to improve our craft, expand opportunity, and leave something stronger behind." },
];

export default function AboutPage() {
  return (
    <div className="lea-motion-page about-page min-h-screen bg-[#fffdfb] text-[#17131a] selection:bg-[#f47945]/25">
      <ScrollMotion />
      <div aria-hidden="true" className="lea-scroll-progress"><span /></div>
      <LandingNav />

      <main>
        <section className="relative isolate min-h-[340px] overflow-hidden bg-[#1f0d2e] text-white sm:min-h-[380px] lg:min-h-[410px]">
          <div aria-hidden="true" className="absolute inset-0"><Image src="/about.jpg" alt="" fill sizes="100vw" priority className="lea-scroll-image scale-[1.04] object-cover blur-[4px]" /><div className="absolute inset-0 bg-gradient-to-r from-[#1f0d2e]/90 via-[#1f0d2e]/60 to-[#1f0d2e]/15" /><div className="absolute inset-0 bg-gradient-to-t from-[#1f0d2e]/70 via-transparent to-[#1f0d2e]/20" /></div>
          <div data-scroll-reveal data-reveal="left" className="relative mx-auto flex min-h-[340px] max-w-[1440px] items-center px-5 py-12 sm:min-h-[380px] sm:px-10 sm:py-14 lg:min-h-[410px] lg:px-[7vw]"><div className="max-w-[760px]"><h1 className="mt-0 max-w-[700px] text-[clamp(2rem,3.4vw,3.25rem)] font-semibold leading-[0.98] tracking-[-0.055em] text-white">Built for <span className="text-[#f47945]">forward motion.</span></h1><p className="mt-5 max-w-[540px] text-sm leading-6 text-white/85 sm:text-base sm:leading-7">Practical learning, human guidance, and opportunity—helping people build skills for the digital economy.</p><div className="mt-7 flex flex-wrap gap-4"><Link href="#story" className="inline-flex items-center gap-3 rounded-full bg-[#f47945] px-5 py-3 text-xs font-semibold text-[#351039] transition hover:bg-white">Read our story <ArrowRight className="h-4 w-4" /></Link><Link href="#mission" className="inline-flex items-center border-b border-white/45 pb-1 text-xs font-medium text-white transition hover:border-[#f47945] hover:text-[#f47945]">Our mission <span className="ml-2">↗</span></Link></div></div></div>
        </section>

        <section id="story" className="scroll-mt-20 bg-white px-5 py-12 sm:px-10 sm:py-14 lg:px-[7vw] lg:py-20">
          <div className="mx-auto grid max-w-[1440px] items-stretch gap-8 lg:grid-cols-[0.95fr_1.05fr] lg:gap-16">
            <div data-scroll-reveal data-reveal="left" className="group relative min-h-[320px] overflow-hidden bg-[#f2f0ed] shadow-[0_18px_45px_rgba(77,23,110,0.12)] sm:min-h-[460px]"><img src={MENTOR_IMAGE} alt="A mentor supporting a learner at LEA Labs" className="lea-scroll-image absolute inset-0 h-full w-full object-cover object-center transition duration-700 group-hover:scale-105" /></div>
            <div data-scroll-reveal data-reveal="right" data-scroll-delay="1" className="flex max-w-[650px] flex-col justify-between"><div><p className="text-base font-semibold uppercase tracking-[0.12em] text-[#f47945]">About LEA LABS</p><h2 className="mt-4 max-w-[500px] text-[clamp(1.75rem,2.8vw,3rem)] font-medium leading-[0.96] tracking-[-0.06em] text-[#151116]">Learning should lead to <span className="text-[#4d176e]">something real.</span></h2><div className="mt-6 space-y-5 text-sm leading-7 text-[#6e6072]"><p>The world is moving quickly. People need more than information; they need the confidence to use what they know.</p><p>LEA Labs exists to close the distance between learning and doing. We create room for people to practise, make mistakes, receive guidance, and leave with work they can show.</p><p>That work is the beginning of a wider journey: learning can fuel innovation, innovation can create solutions, and enterprise can turn those solutions into lasting impact.</p></div></div><div className="mt-8 grid gap-4 sm:grid-cols-[1.1fr_0.9fr]"><div className="bg-white p-5 text-[#351039] shadow-[0_12px_32px_rgba(31,13,46,0.08)] sm:p-6"><p className="text-[10px] font-bold uppercase tracking-[0.18em] text-[#f47945]">Learn · Evolve · Advance</p><p className="mt-4 text-xl font-medium leading-tight tracking-[-0.04em]">Build the confidence to make your next move.</p></div><div className="border-l-4 border-[#4d176e] bg-white p-5 text-sm leading-6 text-[#6e6072] shadow-[0_12px_32px_rgba(31,13,46,0.08)] sm:p-6">Practical learning, human guidance, and a community that keeps progress moving.</div></div></div>
          </div>
        </section>

        <section id="mission" className="scroll-mt-20 bg-[#1f0d2e] px-5 py-8 text-white sm:px-10 sm:py-10 lg:px-[7vw] lg:py-12">
          <div className="mx-auto max-w-[1440px]"><div className="mb-4 flex items-end justify-between"><h2 className="text-[clamp(1.9rem,3vw,3.4rem)] font-medium leading-[0.85] tracking-[-0.075em] text-white">Vision <span className="text-[#f47945]">&amp;</span> Mission</h2><span className="hidden text-xs text-white/45 sm:block">Learn → build → contribute</span></div><div className="flex flex-col gap-4 md:grid md:grid-cols-2"><article className="group relative w-full min-w-0 aspect-[1.35/1] overflow-hidden bg-[#351039]"><img src={ABOUT_HERO_IMAGE} alt="LEA learners looking toward a future shaped by technology" className="absolute inset-0 h-full w-full object-cover transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-[#1f0d2e]/95 via-[#1f0d2e]/58 to-[#4d176e]/20" /><div className="absolute inset-x-0 bottom-0 p-5 sm:p-7"><div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-[#f7c2aa]"><Lightbulb className="h-3.5 w-3.5" /> Vision</div><h3 className="mt-2 max-w-[420px] text-[clamp(1.35rem,2.2vw,2rem)] font-medium leading-[0.98] tracking-[-0.04em] text-white">Make LEA a launchpad for digital possibility.</h3><p className="mt-3 max-w-[500px] text-sm leading-6 text-white/75">To be the ultimate global launchpad for digital talent and sustainable tech enterprises—making a smarter, more inclusive future possible.</p></div></article><article className="group relative w-full min-w-0 aspect-[1.35/1] overflow-hidden bg-[#351039]"><img src={MENTOR_IMAGE} alt="LEA learners building a practical digital project together" className="absolute inset-0 h-full w-full object-cover transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-[#1f0d2e]/95 via-[#1f0d2e]/58 to-[#4d176e]/20" /><div className="absolute inset-x-0 bottom-0 p-5 sm:p-7"><div className="flex items-center gap-2 text-[10px] font-semibold uppercase tracking-[0.18em] text-[#f7c2aa]"><Compass className="h-3.5 w-3.5" /> Mission</div><h3 className="mt-2 max-w-[420px] text-[clamp(1.35rem,2.2vw,2rem)] font-medium leading-[0.98] tracking-[-0.04em] text-white">Build an ecosystem where learning creates movement.</h3><p className="mt-3 max-w-[500px] text-sm leading-6 text-white/75">To build an ecosystem where learning fuels innovation, innovation creates solutions, and enterprise drives lasting impact.</p></div></article></div></div>
        </section>

        <section id="values" className="scroll-mt-20 bg-white px-5 py-12 sm:px-10 sm:py-14 lg:px-[7vw] lg:py-20">
          <div className="mx-auto max-w-[1440px]"><MobileCarousel ariaLabel="core values" className="mt-0 -mx-5 px-5 sm:mx-0 sm:px-0" showControls={false} header={<div className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><h2 className="mt-0 max-w-[560px] text-[clamp(1.75rem,2.8vw,3rem)] font-medium leading-[0.98] tracking-[-0.06em] text-[#151116]">The principles behind the <span className="text-[#1f0d2e]">work.</span></h2></div><p className="max-w-[380px] text-sm leading-7 text-[#6e6072]">Our values shape the way we learn, build, collaborate, and contribute.</p></div>}><div className="flex w-[calc(200vw-2rem)] gap-6 pt-8 sm:w-auto sm:grid sm:grid-cols-2 lg:grid-cols-4">{values.map((value) => <article key={value.title} className="min-w-[calc(50vw-1.75rem)] min-h-[240px] snap-start border border-[#eadfea] bg-white p-5 text-left shadow-[0_12px_32px_rgba(31,13,46,0.06)] transition duration-300 hover:-translate-y-1 hover:shadow-[0_18px_40px_rgba(31,13,46,0.12)] sm:min-w-0 sm:min-h-[270px] sm:p-6"><h3 className="bg-[#1f0d2e] px-4 py-3 text-base font-semibold leading-tight tracking-[-0.02em] text-white">{value.title}</h3><p className="mt-5 text-sm leading-7 text-[#6e6072]">{value.text}</p></article>)}</div></MobileCarousel></div>
        </section>

        <section id="team" className="scroll-mt-20 bg-[#1f0d2e] text-white"><div className="mx-auto grid max-w-[1600px] lg:grid-cols-[0.95fr_1.05fr]"><div className="relative min-h-[330px] overflow-hidden sm:min-h-[420px]"><img src={ABOUT_HERO_IMAGE} alt="LEA learners gathering around a shared digital project" className="absolute inset-0 h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-tr from-[#1f0d2e]/80 via-[#4d176e]/25 to-[#f47945]/15" /></div><div className="flex items-center px-5 py-10 sm:px-10 sm:py-12 lg:px-16"><div className="max-w-[570px]"><div className="flex items-center gap-3 text-[#f7c2aa]"><Users className="h-5 w-5" /><p className="text-xs font-medium uppercase tracking-[0.18em]">05 · The team</p></div><h2 className="mt-5 text-[clamp(1.75rem,2.8vw,3rem)] font-medium leading-[0.96] tracking-[-0.06em]">Progress is personal. It should never happen <span className="text-[#f47945]">alone.</span></h2><p className="mt-6 text-sm leading-7 text-white/65 sm:text-base">LEA brings together educators, mentors, builders, and community connectors to create the conditions for people and ideas to grow.</p><Link href="/corporate" className="mt-7 inline-flex items-center gap-3 border-b border-[#f47945] pb-2 text-xs font-medium text-[#f7c2aa] transition hover:text-white">Work with LEA <ArrowRight className="h-4 w-4" /></Link></div></div></div></section>

        <section className="bg-white px-5 py-10 sm:px-10 sm:py-12 lg:px-[7vw] lg:py-16"><div className="mx-auto flex max-w-[1440px] flex-col justify-between gap-8 lg:flex-row lg:items-end"><div><p className="text-xs font-medium uppercase tracking-[0.18em] text-[#f47945]">Next step</p><h2 className="mt-5 max-w-[680px] text-[clamp(1.75rem,2.8vw,3rem)] font-medium leading-[0.96] tracking-[-0.06em]">Your next chapter can begin with a <span className="text-[#f47945]">conversation.</span></h2><p className="mt-5 max-w-[620px] text-sm leading-7 text-[#6e6072]">Visit us at Applewood Adams, 13th Floor, Nairobi, or start online by exploring a programme that fits your next move.</p></div><div className="flex flex-col items-start gap-4 lg:items-end"><Link href="mailto:hello@lealabs.africa" className="inline-flex items-center gap-3 bg-[#f47945] px-6 py-3 text-xs font-medium text-[#151116] transition hover:bg-[#151116] hover:text-white">Start a conversation <ArrowRight className="h-4 w-4" /></Link><span className="inline-flex items-center gap-2 text-xs font-medium text-[#151116]"><MapPin className="h-4 w-4 text-[#f47945]" /> Applewood Adams, 13th Floor</span></div></div></section>
      </main>

      <LandingFooter />
    </div>
  );
}
