import Link from "next/link";
import { ArrowRight, Award, BriefcaseBusiness, CheckCircle2, Laptop, Play, Sparkles, UsersRound } from "lucide-react";
import { LandingNav } from "@/components/landing/landing-nav";
import { LandingFooter } from "@/components/landing/landing-footer";
import { CorporateContactForm } from "@/components/landing/corporate-contact-form";

const HERO_IMAGE = "https://leasystem-jgtiwg7u.manus.space/manus-storage/lea-programme-collaboration_c9aa5e6b.jpg";
const FEATURE_IMAGE = "https://leasystem-jgtiwg7u.manus.space/manus-storage/lea-community-launch_f1ae296d.jpg";

const benefits = [
  { icon: UsersRound, title: "Expert facilitators", text: "Learn with experienced practitioners who make complex digital topics clear, relevant, and actionable." },
  { icon: Laptop, title: "Flexible learning", text: "Choose focused workshops, guided cohorts, or tailored pathways that fit the rhythm of your organisation." },
  { icon: Award, title: "Recognised progress", text: "Give your people practical evidence of what they can do through projects, reflection, and completion milestones." },
  { icon: BriefcaseBusiness, title: "Workplace impact", text: "Move beyond attendance. Build the confidence and habits that improve the work after training ends." },
];

const programmes = ["Digital fluency and productivity", "Data, AI, and responsible technology", "Leadership and innovation", "Early-career talent development"];

export default function CorporateTrainingPage() {
  return <div className="min-h-screen bg-[#fbfaf7] text-[#14201e] selection:bg-[#f47945]/25"><LandingNav /><main>
    <section className="bg-[#075b58] px-5 pb-0 pt-10 text-white sm:px-10 sm:pt-14 lg:px-[7vw]"><div className="mx-auto max-w-[1440px] text-center"><div className="flex items-center justify-center gap-2 text-xs text-[#f7c2aa]"><Sparkles className="h-4 w-4" /><span>Practical learning for ambitious teams</span><Sparkles className="h-4 w-4" /></div><h1 className="mx-auto mt-7 max-w-[900px] text-[clamp(3rem,6vw,6.6rem)] font-medium leading-[.92] tracking-[-.06em]">Master new skills with <span className="text-[#f7c2aa]">LEA Labs.</span></h1><p className="mx-auto mt-6 max-w-[690px] text-base leading-7 text-white/75 sm:text-lg">Corporate training designed to give your people the skills, confidence, and practical experience to move your organisation forward.</p><Link href="#contact" className="mt-8 inline-flex items-center gap-3 rounded-full bg-[#f47945] px-7 py-4 text-sm font-semibold text-[#351039] transition hover:bg-white">Design your programme <ArrowRight className="h-4 w-4" /></Link><div className="mt-10 flex flex-wrap justify-center gap-x-8 gap-y-3 text-xs text-white/75"><span className="inline-flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-[#f7c2aa]" /> Practical projects</span><span className="inline-flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-[#f7c2aa]" /> Expert facilitation</span><span className="inline-flex items-center gap-2"><CheckCircle2 className="h-4 w-4 text-[#f7c2aa]" /> Built around your context</span></div><div className="relative mx-auto mt-12 max-w-[1120px] translate-y-1/4 overflow-hidden rounded-2xl border-4 border-white/20 bg-[#123f3d] shadow-2xl"><img src={HERO_IMAGE} alt="A team collaborating during a LEA Labs training session" className="aspect-[16/7] w-full object-cover" /><div className="absolute inset-0 bg-[#075b58]/25" /><div className="absolute inset-0 flex items-center justify-center"><span className="flex h-16 w-16 items-center justify-center rounded-full bg-white text-[#075b58] shadow-xl transition hover:scale-105"><Play className="ml-1 h-6 w-6 fill-current" /></span></div></div></div></section>

    <section className="px-5 pb-20 pt-32 sm:px-10 sm:pt-40 lg:px-[7vw]"><div className="mx-auto max-w-[1440px]"><div className="mx-auto max-w-[780px] text-center"><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#f47945]">Why organisations choose LEA</p><h2 className="mt-5 text-[clamp(2.5rem,4.7vw,5rem)] font-medium leading-[.9] tracking-[-.06em]">Learning that makes a difference <span className="text-[#075b58]">at work.</span></h2><p className="mt-6 text-base leading-8 text-[#6b6964]">Strong teams are built through consistent practice, useful feedback, and learning that is connected to the decisions people make every day.</p></div><div className="mt-14 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{benefits.map(({ icon: Icon, title, text }, index) => <article key={title} className={`rounded-xl border border-[#dedbd3] p-6 ${index === 0 ? "bg-[#075b58] text-white" : "bg-white"}`}><div className={`flex h-11 w-11 items-center justify-center rounded-full ${index === 0 ? "bg-white/15 text-[#f7c2aa]" : "bg-[#e6f1ef] text-[#075b58]"}`}><Icon className="h-5 w-5" /></div><h3 className="mt-10 text-xl font-medium tracking-[-.035em]">{title}</h3><p className={`mt-3 text-sm leading-7 ${index === 0 ? "text-white/70" : "text-[#6b6964]"}`}>{text}</p></article>)}</div></div></section>

    <section className="bg-[#edf4f1] px-5 py-20 sm:px-10 lg:px-[7vw]"><div className="mx-auto grid max-w-[1440px] gap-12 lg:grid-cols-[1.05fr_.95fr] lg:items-center"><div className="relative overflow-hidden rounded-2xl bg-[#075b58]"><img src={FEATURE_IMAGE} alt="Learners connecting and collaborating through a shared programme" className="aspect-[1.15/1] w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-tr from-[#075b58]/75 via-transparent to-[#f47945]/15" /><div className="absolute bottom-6 left-6 right-6 flex items-end justify-between text-white"><div><p className="text-xs uppercase tracking-[.18em] text-[#f7c2aa]">Learning in motion</p><p className="mt-2 text-2xl tracking-[-.04em]">From capability to contribution.</p></div><span className="flex h-11 w-11 items-center justify-center rounded-full bg-[#f47945] text-[#351039]"><ArrowRight className="h-5 w-5" /></span></div></div><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#f47945]">What we train</p><h2 className="mt-5 max-w-[600px] text-[clamp(2.5rem,4.4vw,4.8rem)] font-medium leading-[.9] tracking-[-.06em]">Give your team room to <span className="text-[#075b58]">grow.</span></h2><p className="mt-6 max-w-[560px] text-base leading-8 text-[#6b6964]">Our corporate programmes are shaped around the capability your organisation needs next. We combine clear teaching, guided practice, and real conversation so people leave ready to use what they learned.</p><div className="mt-8 grid gap-3 sm:grid-cols-2">{programmes.map((programme) => <div key={programme} className="flex items-start gap-3 text-sm leading-6"><CheckCircle2 className="mt-1 h-4 w-4 shrink-0 text-[#f47945]" />{programme}</div>)}</div><Link href="#contact" className="mt-9 inline-flex items-center gap-2 border-b border-[#075b58] pb-2 text-sm font-semibold text-[#075b58]">Explore a tailored pathway <ArrowRight className="h-4 w-4" /></Link></div></div></section>

    <section className="px-5 py-20 sm:px-10 lg:px-[7vw]"><div className="mx-auto max-w-[1440px]"><div className="grid gap-8 border-b border-[#d8d5cf] pb-10 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#f47945]">How it works</p><h2 className="mt-5 max-w-[560px] text-[clamp(2.5rem,4.4vw,4.8rem)] font-medium leading-[.9] tracking-[-.06em]">A clear route from learning to <span className="text-[#075b58]">impact.</span></h2></div><p className="max-w-[500px] text-base leading-8 text-[#6b6964]">We start with the outcome in mind, then design the learning experience that helps your people reach it.</p></div><div className="grid gap-8 pt-10 md:grid-cols-3">{[["01", "Understand", "We listen to your goals, your people, and the context behind the capability need."], ["02", "Build", "We deliver a focused mix of workshops, practice, projects, and feedback."], ["03", "Embed", "We help teams carry the learning into everyday work and keep momentum going."]].map(([n, title, text]) => <article key={n}><span className="text-sm font-semibold text-[#f47945]">{n}</span><h3 className="mt-6 text-2xl font-medium tracking-[-.04em]">{title}</h3><p className="mt-3 max-w-[300px] text-sm leading-7 text-[#6b6964]">{text}</p></article>)}</div></div></section>

    <section id="contact" className="scroll-mt-16 bg-[#075b58] px-5 py-20 text-white sm:px-10 lg:px-[7vw]"><div className="mx-auto grid max-w-[1440px] gap-12 lg:grid-cols-[.85fr_1.15fr] lg:items-start"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#f7c2aa]">Start a conversation</p><h2 className="mt-5 max-w-[620px] text-[clamp(2.7rem,5vw,5.3rem)] font-medium leading-[.88] tracking-[-.06em]">Make learning work harder for your <span className="text-[#f7c2aa]">organisation.</span></h2><p className="mt-6 max-w-[480px] text-base leading-8 text-white/70">Share what your team is working toward. We’ll help you find a practical starting point.</p></div><CorporateContactForm /></div></section>
  </main><LandingFooter /></div>;
}

export const metadata = { title: "Corporate Training | LEA Labs", description: "Professional corporate training for digital capability, leadership, innovation, and workplace impact." };
