import Link from "next/link";
import { ArrowDownRight, ArrowRight, Check, MoveUpRight } from "lucide-react";
import { LandingNav } from "@/components/landing/landing-nav";
import { LandingFooter } from "@/components/landing/landing-footer";
import { CorporateContactForm } from "@/components/landing/corporate-contact-form";

const HERO_IMAGE = "https://leasystem-jgtiwg7u.manus.space/manus-storage/lea-programme-collaboration_c9aa5e6b.jpg";
const TEAM_IMAGE = "https://leasystem-jgtiwg7u.manus.space/manus-storage/lea-community-launch_f1ae296d.jpg";

const offers = [
  ["01", "Digital fluency", "Help teams work with software, data, AI, and modern digital tools with confidence."],
  ["02", "Leadership for change", "Equip managers to lead transformation, make better decisions, and create room for innovation."],
  ["03", "Early-career pathways", "Build a stronger talent pipeline through structured cohorts, practical projects, and mentorship."],
];

const proof = ["Built around your business context", "Practical work, not passive content", "Facilitated by people who understand the work", "Progress you can see and keep building on"];

export default function CorporateTrainingPage() {
  return <div className="min-h-screen bg-[#f7f5f1] text-[#16141a] selection:bg-[#f47945]/25"><LandingNav /><main>
    <section className="border-b border-[#d8d2ca] px-5 pb-14 pt-8 sm:px-10 sm:pb-20 sm:pt-12 lg:px-[7vw]"><div className="mx-auto max-w-[1440px]"><div className="flex items-start justify-between gap-8"><p className="text-[10px] font-semibold uppercase tracking-[.22em] text-[#4d176e]">LEA Labs / Corporate</p><p className="hidden text-right text-[10px] uppercase tracking-[.18em] text-[#847a83] sm:block">Capability building<br />for what comes next</p></div><div className="mt-20 grid gap-12 lg:grid-cols-[1.05fr_.95fr] lg:items-end lg:gap-20"><div><h1 className="max-w-[850px] text-[clamp(3.5rem,7vw,8rem)] font-medium leading-[.86] tracking-[-.055em]">Build the<br /><span className="text-[#4d176e]">capability</span><br />to move.</h1><p className="mt-9 max-w-[560px] text-base leading-8 text-[#5f5760] sm:text-lg">We help organisations turn learning into a practical advantage—giving teams the digital skills, confidence, and momentum to do better work.</p><div className="mt-9 flex flex-wrap items-center gap-6"><Link href="#contact" className="inline-flex items-center gap-3 bg-[#f47945] px-6 py-4 text-sm font-semibold text-[#351039] transition hover:bg-[#4d176e] hover:text-white">Start a conversation <ArrowRight className="h-4 w-4" /></Link><Link href="#approach" className="inline-flex items-center gap-2 text-sm font-semibold text-[#4d176e]">Our approach <ArrowDownRight className="h-4 w-4" /></Link></div></div><div className="relative"><div className="aspect-[1.15/1] overflow-hidden bg-[#1f0d2e]"><img src={HERO_IMAGE} alt="A team collaborating during a learning session" className="h-full w-full object-cover grayscale-[.15]" /><div className="absolute inset-0 bg-gradient-to-tr from-[#1f0d2e]/55 via-transparent to-[#f47945]/10" /></div><p className="mt-3 flex justify-between text-[10px] uppercase tracking-[.16em] text-[#847a83]"><span>Learning in context</span><span>01 / 04</span></p></div></div></div></section>

    <section className="bg-[#1f0d2e] px-5 py-9 text-white sm:px-10 lg:px-[7vw]"><div className="mx-auto grid max-w-[1440px] gap-6 sm:grid-cols-3 sm:gap-10"><div><p className="text-3xl font-medium tracking-[-.05em] text-[#f47945]">Learn</p><p className="mt-2 max-w-[220px] text-sm leading-6 text-white/60">Make learning relevant to the work your people already do.</p></div><div><p className="text-3xl font-medium tracking-[-.05em] text-[#f7c2aa]">Apply</p><p className="mt-2 max-w-[220px] text-sm leading-6 text-white/60">Turn new skills into projects, habits, and better decisions.</p></div><div><p className="text-3xl font-medium tracking-[-.05em] text-white">Advance</p><p className="mt-2 max-w-[220px] text-sm leading-6 text-white/60">Build the confidence and capability for what comes next.</p></div></div></section>

    <section id="approach" className="scroll-mt-16 px-5 py-20 sm:px-10 lg:px-[7vw]"><div className="mx-auto max-w-[1440px]"><div className="flex flex-col justify-between gap-6 border-b border-[#d8d2ca] pb-8 lg:flex-row lg:items-end"><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-[#f47945]">02 / What we do</p><h2 className="mt-5 max-w-[720px] text-[clamp(2.6rem,4.8vw,5.2rem)] font-medium leading-[.88] tracking-[-.06em]">Training designed for the <span className="text-[#4d176e]">real world.</span></h2></div><p className="max-w-[360px] text-sm leading-7 text-[#6f6670]">No off-the-shelf answers. We create focused learning experiences around your people, your priorities, and the change you want to make.</p></div><div className="mt-10 divide-y divide-[#d8d2ca]">{offers.map(([number, title, text]) => <article key={number} className="grid gap-5 py-7 sm:grid-cols-[80px_1fr_1fr] sm:items-start"><span className="text-xs font-semibold text-[#f47945]">{number}</span><h3 className="text-2xl font-medium tracking-[-.04em] text-[#17131a]">{title}</h3><p className="max-w-[380px] text-sm leading-7 text-[#6f6670]">{text}</p></article>)}</div></div></section>

    <section className="bg-[#e9e0ef] px-5 py-20 sm:px-10 lg:px-[7vw]"><div className="mx-auto grid max-w-[1440px] gap-12 lg:grid-cols-[.85fr_1.15fr] lg:items-center"><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-[#4d176e]">03 / Why LEA</p><h2 className="mt-5 max-w-[560px] text-[clamp(2.6rem,4.5vw,4.8rem)] font-medium leading-[.88] tracking-[-.06em]">Make capability a <span className="text-[#f47945]">competitive edge.</span></h2></div><div className="grid gap-0 border-t border-[#c9b8d2]">{proof.map((item) => <div key={item} className="flex items-center gap-4 border-b border-[#c9b8d2] py-5 text-base"><span className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[#4d176e] text-white"><Check className="h-4 w-4" /></span>{item}</div>)}</div></div></section>

    <section className="px-5 py-20 sm:px-10 lg:px-[7vw]"><div className="mx-auto grid max-w-[1440px] gap-10 lg:grid-cols-[1fr_.9fr] lg:items-center"><div className="relative aspect-[1.25/1] overflow-hidden bg-[#1f0d2e]"><img src={TEAM_IMAGE} alt="A diverse group learning together" className="h-full w-full object-cover" /><div className="absolute inset-0 bg-gradient-to-tr from-[#1f0d2e]/65 to-transparent" /><div className="absolute bottom-6 left-6 text-white"><p className="text-[10px] uppercase tracking-[.2em] text-[#f7c2aa]">The outcome</p><p className="mt-2 max-w-[300px] text-2xl leading-tight tracking-[-.04em]">People who are ready to make the next move.</p></div></div><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-[#f47945]">04 / The difference</p><h2 className="mt-5 max-w-[600px] text-[clamp(2.6rem,4.5vw,4.8rem)] font-medium leading-[.88] tracking-[-.06em]">From a training session to a <span className="text-[#4d176e]">new way of working.</span></h2><p className="mt-6 max-w-[500px] text-base leading-8 text-[#6f6670]">The best learning does not end when the session ends. We create the conditions for people to practise, share, and keep improving after we leave the room.</p><Link href="#contact" className="mt-8 inline-flex items-center gap-2 border-b border-[#4d176e] pb-2 text-sm font-semibold text-[#4d176e]">Explore a programme <MoveUpRight className="h-4 w-4" /></Link></div></div></section>

    <section id="contact" className="scroll-mt-16 bg-[#f47945] px-5 py-20 sm:px-10 lg:px-[7vw]"><div className="mx-auto grid max-w-[1440px] gap-12 lg:grid-cols-[.9fr_1.1fr] lg:items-start"><div><p className="text-[10px] font-semibold uppercase tracking-[.2em] text-[#351039]">05 / Start here</p><h2 className="mt-5 max-w-[600px] text-[clamp(2.8rem,5vw,5.5rem)] font-medium leading-[.86] tracking-[-.06em] text-[#351039]">Let’s make the next move <span className="text-white">practical.</span></h2><p className="mt-6 max-w-[470px] text-base leading-8 text-[#351039]/75">Tell us where your team is going and where capability needs to catch up. We’ll help you find a useful place to begin.</p></div><div className="text-[#17131a]"><CorporateContactForm /></div></div></section>
  </main><LandingFooter /></div>;
}

export const metadata = { title: "Corporate Training | LEA Labs", description: "Corporate training and capability building designed around the real work of modern organisations." };
