"use client";

import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { BookOpen, ClipboardCheck, FolderOpen, LineChart, Loader2, Megaphone, MessageSquare, Send, Video } from "lucide-react";
import { toast } from "sonner";
import { api } from "@/lib/api-client";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Badge } from "@/components/ui/badge";
import { InstructorGrading } from "@/components/modules/instructor-grading";

type Row = Record<string, unknown>;
interface WorkspaceResponse { data: Row[]; meta?: { total?: number; statuses?: Record<string, number>; assigned_course_ids?: string[] } }
function str(row: Row | undefined, ...keys: string[]) { for (const key of keys) { const value = row?.[key]; if (value !== undefined && value !== null && String(value) !== "") return String(value); } return ""; }
function titleOf(row: Row) { return str(row, "course_title", "title", "name") || "Untitled"; }
function useWorkspace(resource: string) { return useQuery({ queryKey: ["instructor-workspace", resource], queryFn: () => api.get<WorkspaceResponse>(`/instructor/workspace?resource=${encodeURIComponent(resource)}`) }); }
function CourseSelect({ courses, value, onChange }: { courses: Row[]; value: string; onChange: (value: string) => void }) { return <select value={value} onChange={(event) => onChange(event.target.value)} className="h-10 w-full border border-input bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-[#f47945]">{courses.length ? <option value="">Select course</option> : <option value="">No assigned courses</option>}{courses.map((course) => <option key={str(course, "id")} value={str(course, "id")}>{titleOf(course)}</option>)}</select>; }
function Empty({ text }: { text: string }) { return <div className="border border-dashed border-border bg-[#fffdfb] p-8 text-center text-sm text-muted-foreground">{text}</div>; }
function WorkspaceShell({ icon: Icon, title, children }: { icon: typeof BookOpen; title: string; children: React.ReactNode }) { return <div className="space-y-5"><div className="flex items-start gap-3"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-[#f6eef9] text-[#4d176e]"><Icon className="h-5 w-5" /></div><div><h2 className="text-xl font-semibold text-[#4d176e]">{title}</h2><p className="mt-1 text-sm text-muted-foreground">Keep learner-facing teaching work connected to the assigned course evidence.</p></div></div>{children}</div>; }

function ClassesView() {
  const courses = useWorkspace("courses"); const classes = useWorkspace("classes");
  return <WorkspaceShell icon={BookOpen} title="My classes and course guide"><div className="grid gap-4 lg:grid-cols-2">{courses.data?.data.map((course) => <Card key={str(course, "id")} className="rounded-[1.25rem]"><CardHeader><CardTitle className="text-base text-[#4d176e]">{titleOf(course)}</CardTitle><p className="text-xs text-muted-foreground">{str(course, "programme", "programme_title")}</p></CardHeader><CardContent><div className="grid gap-2 sm:grid-cols-3"><div className="border bg-[#fffdfb] p-3"><p className="text-xs text-muted-foreground">Lessons</p><p className="mt-1 text-lg font-semibold">{Array.isArray(course.lessons) ? course.lessons.length : Number(course.lesson_count ?? 0)}</p></div><div className="border bg-[#fffdfb] p-3"><p className="text-xs text-muted-foreground">Learners</p><p className="mt-1 text-lg font-semibold">{Number(course.learner_count ?? 0)}</p></div><div className="border bg-[#fffdfb] p-3"><p className="text-xs text-muted-foreground">Status</p><Badge className="mt-2">{str(course, "status") || "active"}</Badge></div></div><p className="mt-4 text-sm leading-6 text-muted-foreground">Use the lesson sequence as your teaching guide, post a course announcement, and monitor evidence from the grading queue.</p></CardContent></Card>)}{!courses.isLoading && !courses.data?.data.length ? <Empty text="No courses are assigned to this instructor yet. Ask an administrator to assign a course or class." /> : null}</div><Card className="rounded-[1.25rem]"><CardHeader><CardTitle className="text-base text-[#4d176e]">Scheduled teaching sessions</CardTitle></CardHeader><CardContent>{classes.isLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : classes.data?.data.length ? <div className="grid gap-3 md:grid-cols-2">{classes.data.data.map((row) => <div key={str(row, "id")} className="border bg-[#fffdfb] p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{titleOf(row)}</p><p className="mt-1 text-xs text-muted-foreground">{str(row, "start_time", "date")} · {str(row, "venue", "meetingPlatform") || "Online or classroom"}</p></div><Badge variant="outline">{str(row, "status") || "scheduled"}</Badge></div>{str(row, "meetingLink", "meeting_link") ? <Button asChild size="sm" variant="outline" className="mt-3"><a href={str(row, "meetingLink", "meeting_link")} target="_blank" rel="noreferrer"><Video className="mr-1.5 h-4 w-4" /> Join link</a></Button> : null}</div>)}</div> : <Empty text="No scheduled classes or tutor sessions are assigned yet." />}</CardContent></Card></WorkspaceShell>;
}

function AttendanceView() {
  const queryClient = useQueryClient(); const courses = useWorkspace("courses"); const learners = useWorkspace("learners"); const attendance = useWorkspace("attendance");
  const [form, setForm] = useState({ courseId: "", learnerId: "", date: new Date().toISOString().slice(0, 10), status: "present", notes: "" });
  const save = useMutation({ mutationFn: () => api.post(`/instructor/workspace`, { resource: "attendance", ...form }), onSuccess: () => { toast.success("Attendance saved."); setForm((current) => ({ ...current, learnerId: "", notes: "" })); void queryClient.invalidateQueries({ queryKey: ["instructor-workspace", "attendance"] }); }, onError: (error) => toast.error(error instanceof Error ? error.message : "Unable to save attendance.") });
  return <WorkspaceShell icon={ClipboardCheck} title="Attendance management"><div className="grid gap-5 lg:grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)]"><Card className="rounded-[1.25rem]"><CardHeader><CardTitle className="text-base">Mark learner attendance</CardTitle></CardHeader><CardContent className="space-y-3"><CourseSelect courses={courses.data?.data ?? []} value={form.courseId} onChange={(value) => setForm({ ...form, courseId: value })} /><select value={form.learnerId} onChange={(event) => setForm({ ...form, learnerId: event.target.value })} className="h-10 w-full border border-input bg-background px-3 text-sm"><option value="">Select learner</option>{(learners.data?.data ?? []).map((learner) => <option key={str(learner, "id")} value={str(learner, "id")}>{str(learner, "name", "email")}</option>)}</select><Input type="date" value={form.date} onChange={(event) => setForm({ ...form, date: event.target.value })} /><select value={form.status} onChange={(event) => setForm({ ...form, status: event.target.value })} className="h-10 w-full border border-input bg-background px-3 text-sm"><option value="present">Present</option><option value="late">Late</option><option value="absent">Absent</option><option value="excused">Excused</option></select><Textarea placeholder="Optional note" value={form.notes} onChange={(event) => setForm({ ...form, notes: event.target.value })} /><Button disabled={save.isPending || !form.courseId || !form.learnerId} onClick={() => save.mutate()} className="w-full bg-[#4d176e] hover:bg-[#35104f]">{save.isPending ? "Saving…" : "Save attendance"}</Button></CardContent></Card><Card className="rounded-[1.25rem]"><CardHeader><CardTitle className="text-base">Recent attendance records</CardTitle></CardHeader><CardContent>{attendance.isLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : attendance.data?.data.length ? <div className="space-y-2">{attendance.data.data.slice(0, 20).map((row) => <div key={str(row, "id")} className="flex items-center justify-between gap-3 border bg-[#fffdfb] p-3 text-sm"><div><p className="font-medium">{str(row, "learner_name", "learnerId")}</p><p className="text-xs text-muted-foreground">{titleOf(row)} · {str(row, "date", "created_at")}</p></div><Badge variant={str(row, "status") === "present" ? "default" : str(row, "status") === "absent" ? "destructive" : "secondary"}>{str(row, "status")}</Badge></div>)}</div> : <Empty text="No attendance records have been marked yet." />}</CardContent></Card></div></WorkspaceShell>;
}

function AnnouncementsView() {
  const queryClient = useQueryClient(); const courses = useWorkspace("courses"); const announcements = useWorkspace("announcements");
  const [form, setForm] = useState({ courseId: "", title: "", body: "" });
  const save = useMutation({ mutationFn: () => api.post(`/instructor/workspace`, { resource: "announcements", ...form }), onSuccess: () => { toast.success("Announcement published and learners notified."); setForm({ courseId: "", title: "", body: "" }); void queryClient.invalidateQueries({ queryKey: ["instructor-workspace", "announcements"] }); }, onError: (error) => toast.error(error instanceof Error ? error.message : "Unable to publish announcement.") });
  return <WorkspaceShell icon={Megaphone} title="Course announcements"><div className="grid gap-5 lg:grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)]"><Card className="rounded-[1.25rem]"><CardHeader><CardTitle className="text-base">Post to a course</CardTitle></CardHeader><CardContent className="space-y-3"><CourseSelect courses={courses.data?.data ?? []} value={form.courseId} onChange={(value) => setForm({ ...form, courseId: value })} /><Input placeholder="Announcement title" value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /><Textarea className="min-h-32" placeholder="Write the update, deadline, or teaching guidance…" value={form.body} onChange={(event) => setForm({ ...form, body: event.target.value })} /><Button disabled={save.isPending || !form.courseId || !form.title || !form.body} onClick={() => save.mutate()} className="w-full bg-[#4d176e] hover:bg-[#35104f]"><Send className="mr-1.5 h-4 w-4" />{save.isPending ? "Publishing…" : "Publish announcement"}</Button></CardContent></Card><Card className="rounded-[1.25rem]"><CardHeader><CardTitle className="text-base">Published updates</CardTitle></CardHeader><CardContent>{announcements.isLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : announcements.data?.data.length ? <div className="space-y-3">{announcements.data.data.map((row) => <div key={str(row, "id")} className="border bg-[#fffdfb] p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{str(row, "title")}</p><p className="mt-1 text-xs text-muted-foreground">{titleOf(row)} · {str(row, "created_at", "updated_at")}</p></div><Badge>{str(row, "published") === "false" ? "Draft" : "Published"}</Badge></div><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-muted-foreground">{str(row, "body", "content")}</p></div>)}</div> : <Empty text="No announcements have been posted yet." />}</CardContent></Card></div></WorkspaceShell>;
}

function MaterialsView() {
  const queryClient = useQueryClient(); const courses = useWorkspace("courses"); const materials = useWorkspace("materials");
  const [form, setForm] = useState({ courseId: "", title: "", url: "", category: "lesson material", description: "" });
  const [file, setFile] = useState<File | null>(null); const [fileInputKey, setFileInputKey] = useState(0);
  const save = useMutation({
    mutationFn: async () => {
      if (file) {
        const payload = new FormData();
        payload.append("file", file); payload.append("courseId", form.courseId); payload.append("title", form.title); payload.append("category", form.category); payload.append("description", form.description);
        return api.post(`/instructor/workspace/upload`, payload);
      }
      return api.post(`/instructor/workspace`, { resource: "materials", ...form });
    },
    onSuccess: () => { toast.success(file ? "Material uploaded and learners notified." : "Teaching material saved."); setForm({ courseId: "", title: "", url: "", category: "lesson material", description: "" }); setFile(null); setFileInputKey((value) => value + 1); void queryClient.invalidateQueries({ queryKey: ["instructor-workspace", "materials"] }); },
    onError: (error) => toast.error(error instanceof Error ? error.message : "Unable to save material."),
  });
  const remove = useMutation({ mutationFn: (id: string) => api.delete(`/instructor/workspace/${id}?resource=materials`), onSuccess: () => { toast.success("Material removed."); void queryClient.invalidateQueries({ queryKey: ["instructor-workspace", "materials"] }); }, onError: (error) => toast.error(error instanceof Error ? error.message : "Unable to remove material.") });
  const canSave = Boolean(form.courseId && ((file && file.size > 0) || (!file && form.title && form.url)));
  return <WorkspaceShell icon={FolderOpen} title="Teaching materials"><div className="grid gap-5 lg:grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)]"><Card className="rounded-[1.25rem]"><CardHeader><CardTitle className="text-base">Upload a course resource</CardTitle><p className="text-xs text-muted-foreground">Files are stored on the LEA local document volume, not paid Firebase Storage.</p></CardHeader><CardContent className="space-y-3"><CourseSelect courses={courses.data?.data ?? []} value={form.courseId} onChange={(value) => setForm({ ...form, courseId: value })} /><Input placeholder="Material title (optional for files)" value={form.title} onChange={(event) => setForm({ ...form, title: event.target.value })} /><Input key={fileInputKey} type="file" accept=".pdf,.ppt,.pptx,.doc,.docx,.xls,.xlsx,.txt,.md,.csv,.zip,.png,.jpg,.jpeg" onChange={(event) => setFile(event.target.files?.[0] ?? null)} /><p className="text-xs text-muted-foreground">{file ? `${file.name} · ${(file.size / 1024 / 1024).toFixed(1)} MB` : "Choose a PDF, slide deck, lab file, or document up to 25 MB."}</p><Input placeholder="Or add an external URL" value={form.url} onChange={(event) => setForm({ ...form, url: event.target.value })} /><Input placeholder="Category" value={form.category} onChange={(event) => setForm({ ...form, category: event.target.value })} /><Textarea placeholder="How should learners use this?" value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} /><Button disabled={save.isPending || !canSave} onClick={() => save.mutate()} className="w-full bg-[#4d176e] hover:bg-[#35104f]">{save.isPending ? "Saving…" : file ? "Upload and publish" : "Save external resource"}</Button></CardContent></Card><Card className="rounded-[1.25rem]"><CardHeader><CardTitle className="text-base">Course library</CardTitle></CardHeader><CardContent>{materials.isLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : materials.data?.data.length ? <div className="space-y-3">{materials.data.data.map((row) => <div key={str(row, "id")} className="flex items-start justify-between gap-4 border bg-[#fffdfb] p-4"><div className="min-w-0"><p className="font-medium">{str(row, "title")}</p><p className="mt-1 text-xs text-muted-foreground">{titleOf(row)} · {str(row, "category")} {str(row, "originalName") ? `· ${str(row, "originalName")}` : ""}</p><p className="mt-2 text-xs text-muted-foreground">{str(row, "description")}</p></div><div className="flex shrink-0 gap-2"><Button asChild size="sm" variant="outline"><a href={str(row, "download_url", "url")} target="_blank" rel="noreferrer">Open</a></Button><Button size="sm" variant="ghost" onClick={() => remove.mutate(str(row, "id"))} disabled={remove.isPending}>Remove</Button></div></div>)}</div> : <Empty text="No course materials have been added yet." />}</CardContent></Card></div></WorkspaceShell>;
}

function TutorSessionsView() {
  const queryClient = useQueryClient();
  const requests = useWorkspace("tutor_requests");
  const [editing, setEditing] = useState<string | null>(null);
  const [response, setResponse] = useState("");
  const [meetingLink, setMeetingLink] = useState("");
  const [confirmedDate, setConfirmedDate] = useState("");
  const [confirmedTime, setConfirmedTime] = useState("");
  const [venue, setVenue] = useState("");
  const update = useMutation({
    mutationFn: (payload: { id: string; status: string; response_message: string; meetingLink: string; confirmedDate: string; confirmedTime: string; venue: string }) => api.patch(`/instructor/workspace/${payload.id}`, {
      resource: "tutor_requests",
      status: payload.status,
      response_message: payload.response_message,
      meetingLink: payload.meetingLink,
      meetingPlatform: payload.meetingLink ? "Google Meet" : "",
      confirmedDate: payload.confirmedDate,
      confirmedTime: payload.confirmedTime,
      venue: payload.venue,
    }),
    onSuccess: () => { toast.success("Tutor request updated and learner notified."); setEditing(null); void queryClient.invalidateQueries({ queryKey: ["instructor-workspace", "tutor_requests"] }); },
    onError: (error) => toast.error(error instanceof Error ? error.message : "Unable to update tutor request."),
  });
  return <WorkspaceShell icon={Video} title="Tutor session management"><div className="space-y-3">{requests.isLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : requests.data?.data.length ? requests.data.data.map((row) => {
    const id = str(row, "id");
    const active = editing === id;
    const sessionDate = str(row, "confirmedDate", "confirmed_date");
    const sessionTime = str(row, "confirmedTime", "confirmed_time");
    const sessionVenue = str(row, "venue");
    return <Card key={id} className="rounded-[1.25rem]"><CardContent className="space-y-3 p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="font-medium">{str(row, "learner_name", "learnerId")} · {titleOf(row)}</p><p className="mt-1 text-xs text-muted-foreground">Requested {str(row, "preferredDate", "preferred_date", "created_at")} · {str(row, "mode") || "online"}</p><p className="mt-2 text-sm text-muted-foreground">{str(row, "notes")}</p>{sessionDate || sessionTime || sessionVenue ? <p className="mt-2 text-xs text-[#4d176e]">Scheduled: {sessionDate} {sessionTime}{sessionVenue ? ` · ${sessionVenue}` : ""}</p> : null}</div><Badge variant={str(row, "status") === "confirmed" || str(row, "status") === "scheduled" ? "default" : "secondary"}>{str(row, "status") || "pending"}</Badge></div>{active ? <div className="space-y-3"><Textarea placeholder="Response to learner" value={response} onChange={(event) => setResponse(event.target.value)} /><div className="grid gap-3 sm:grid-cols-3"><Input type="date" value={confirmedDate} onChange={(event) => setConfirmedDate(event.target.value)} /><Input type="time" value={confirmedTime} onChange={(event) => setConfirmedTime(event.target.value)} /><Input placeholder="Venue or room" value={venue} onChange={(event) => setVenue(event.target.value)} /></div><Input placeholder="Google Meet link (required for online sessions)" value={meetingLink} onChange={(event) => setMeetingLink(event.target.value)} /><div className="flex flex-wrap gap-2"><Button size="sm" onClick={() => update.mutate({ id, status: "confirmed", response_message: response, meetingLink, confirmedDate, confirmedTime, venue })} disabled={update.isPending || !confirmedDate || !confirmedTime || (!venue && !meetingLink)}>Confirm and notify learner</Button><Button size="sm" variant="outline" onClick={() => update.mutate({ id, status: "declined", response_message: response, meetingLink, confirmedDate: "", confirmedTime: "", venue: "" })} disabled={update.isPending}>Decline</Button></div></div> : <div className="flex flex-wrap gap-2"><Button size="sm" variant="outline" onClick={() => { setEditing(id); setResponse(str(row, "admin_response", "response_message")); setMeetingLink(str(row, "meetingLink", "meeting_link")); setConfirmedDate(sessionDate || str(row, "preferredDate", "preferred_date")); setConfirmedTime(sessionTime || str(row, "preferredTime", "preferred_time")); setVenue(sessionVenue); }}>Respond / schedule</Button>{str(row, "meetingLink", "meeting_link") ? <Button asChild size="sm" variant="link"><a href={str(row, "meetingLink", "meeting_link")} target="_blank" rel="noreferrer"><Video className="mr-1.5 h-4 w-4" /> Join meeting</a></Button> : null}</div>}</CardContent></Card>;
  }) : <Empty text="No tutor requests are assigned to you." />}</div></WorkspaceShell>;
}

function DiscussionsView() {
  const courses = useWorkspace("courses"); const discussions = useWorkspace("discussions"); const [courseId, setCourseId] = useState(""); const [title, setTitle] = useState(""); const [content, setContent] = useState(""); const [replying, setReplying] = useState<string | null>(null); const [reply, setReply] = useState(""); const queryClient = useQueryClient();
  const post = useMutation({ mutationFn: (payload: Row) => api.post(`/learner/discussions`, payload), onSuccess: () => { toast.success("Discussion update posted."); setTitle(""); setContent(""); setReply(""); setReplying(null); void queryClient.invalidateQueries({ queryKey: ["instructor-workspace", "discussions"] }); }, onError: (error) => toast.error(error instanceof Error ? error.message : "Unable to post discussion update.") });
  const roots = useMemo(() => (discussions.data?.data ?? []).filter((row) => !str(row, "parentId") && str(row, "kind") !== "reply"), [discussions.data]);
  return <WorkspaceShell icon={MessageSquare} title="Discussion moderation"><div className="grid gap-5 lg:grid-cols-[minmax(0,0.8fr)_minmax(0,1.2fr)]"><Card className="rounded-[1.25rem]"><CardHeader><CardTitle className="text-base">Post instructor guidance</CardTitle></CardHeader><CardContent className="space-y-3"><CourseSelect courses={courses.data?.data ?? []} value={courseId} onChange={setCourseId} /><Input placeholder="Topic title" value={title} onChange={(event) => setTitle(event.target.value)} /><Textarea placeholder="Answer a common question or share guidance…" value={content} onChange={(event) => setContent(event.target.value)} /><Button disabled={!courseId || !title || !content || post.isPending} onClick={() => post.mutate({ courseId, title, content, kind: "announcement" })} className="w-full bg-[#4d176e] hover:bg-[#35104f]">Post guidance</Button></CardContent></Card><Card className="rounded-[1.25rem]"><CardHeader><CardTitle className="text-base">Learner threads</CardTitle></CardHeader><CardContent>{discussions.isLoading ? <Loader2 className="h-4 w-4 animate-spin" /> : roots.length ? <div className="space-y-4">{roots.map((row) => { const id = str(row, "id"); const threadId = str(row, "threadId") || id; const threadReplies = (discussions.data?.data ?? []).filter((replyRow) => str(replyRow, "threadId") === threadId && Boolean(str(replyRow, "parentId"))); return <div key={id} className="border bg-[#fffdfb] p-4"><div className="flex items-start justify-between gap-3"><div><p className="font-medium">{str(row, "title")}</p><p className="mt-1 text-xs text-muted-foreground">{str(row, "authorName", "authorId")} · {titleOf(row)}</p></div><Badge variant="outline">{threadReplies.length} replies</Badge></div><p className="mt-3 text-sm leading-6 text-muted-foreground">{str(row, "content")}</p>{threadReplies.map((replyRow) => <div key={str(replyRow, "id")} className="mt-3 border-l-2 border-[#f47945] pl-3 text-sm"><p>{str(replyRow, "content")}</p><p className="mt-1 text-xs text-muted-foreground">{str(replyRow, "authorName")}</p></div>)}{replying === id ? <div className="mt-3 flex gap-2"><Textarea value={reply} onChange={(event) => setReply(event.target.value)} placeholder="Write an instructor reply…" /><Button size="sm" disabled={!reply || post.isPending} onClick={() => post.mutate({ courseId: str(row, "courseId", "course_id"), parentId: id, content: reply })}>Reply</Button></div> : <Button size="sm" variant="outline" className="mt-3" onClick={() => setReplying(id)}>Reply</Button>}</div>; })}</div> : <Empty text="Learner discussion threads will appear here after a question is posted." />}</CardContent></Card></div></WorkspaceShell>;
}

function AnalyticsView() {
  const attendance = useWorkspace("attendance"); const submissions = useWorkspace("submissions"); const learners = useWorkspace("learners");
  const submitted = submissions.data?.data ?? []; const average = submitted.length ? Math.round(submitted.reduce((sum, row) => sum + Number(row.grade ?? 0), 0) / submitted.filter((row) => row.grade !== undefined && row.grade !== null).length || 0) : 0;
  const inactive = (learners.data?.data ?? []).filter((row) => { const date = new Date(str(row, "last_activity", "updated_at", "created_at")).getTime(); return date > 0 && Date.now() - date > 14 * 86400000; });
  return <WorkspaceShell icon={LineChart} title="Learner intervention analytics"><div className="grid gap-3 sm:grid-cols-3"><div className="border bg-[#fffdfb] p-4"><p className="text-xs text-muted-foreground">Attendance records</p><p className="mt-1 text-2xl font-semibold text-[#4d176e]">{attendance.data?.data.length ?? 0}</p></div><div className="border bg-[#fffdfb] p-4"><p className="text-xs text-muted-foreground">Average graded score</p><p className="mt-1 text-2xl font-semibold text-[#4d176e]">{average}%</p></div><div className="border bg-[#fffdfb] p-4"><p className="text-xs text-muted-foreground">Needs intervention</p><p className="mt-1 text-2xl font-semibold text-[#f47945]">{inactive.length}</p></div></div><Card className="rounded-[1.25rem]"><CardHeader><CardTitle className="text-base">Learner intervention list</CardTitle></CardHeader><CardContent>{inactive.length ? <div className="space-y-2">{inactive.map((row) => <div key={str(row, "id")} className="flex items-center justify-between border bg-[#fffdfb] p-3"><div><p className="font-medium">{str(row, "name", "email")}</p><p className="text-xs text-muted-foreground">No activity since {str(row, "last_activity", "updated_at", "created_at")}</p></div><Badge variant="destructive">Follow up</Badge></div>)}</div> : <Empty text="No learners currently meet the inactivity alert threshold." />}</CardContent></Card></WorkspaceShell>;
}

export function InstructorTeachingWorkspace({ slug }: { slug: string }) {
  if (slug === "classes") return <ClassesView />;
  if (slug === "attendance") return <AttendanceView />;
  if (slug === "announcements") return <AnnouncementsView />;
  if (slug === "materials") return <MaterialsView />;
  if (slug === "tutor-sessions") return <TutorSessionsView />;
  if (slug === "discussions") return <DiscussionsView />;
  if (slug === "analytics") return <AnalyticsView />;
  if (slug === "grades" || slug === "assignments") return <InstructorGrading />;
  return <ClassesView />;
}
